import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Breadcrumb from '../components/breadcrumb'
import Search from '../components/search'
import axios from 'axios';
import Category from '../components/category'
import Posts from '../components/posts'
import { useState, useEffect } from 'react';



const Home = (props) => {
  const [posts, setPosts] = useState([]);
  const [counts, setCounts] = useState(0);

  const searchTerm = (term) => {
    let temp = [];

    temp = [...JSON.parse(localStorage.getItem('posts')).filter((obj) =>
      JSON.stringify(obj).toLowerCase().includes(term.toLowerCase())
    )];

    setCounts(temp.length);
    setPosts(temp);

  }

  useEffect(() => {
    if (props.posts) {
      localStorage.setItem('posts', JSON.stringify(props.posts));
      setPosts(props.posts);
      setCounts(props.posts.length)
    }
  }, [props])

  return (
    <>
      <Head>
        <title>Weblog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto lg:w-full max-w-full h-full flex flex-col justify-center items-center pb-80">
        <Header />
        <Breadcrumb />
        <span className="text-3xl">وبلاگ</span>
        <Search onSearch={data => searchTerm(data)} />
        <div className="container flex xl:flex-row md:flex-col-reverse sm:flex-col-reverse xs:flex-col-reverse lg:flex-row xl:w-full xs:items-center lg:w-full">
          <Posts data={posts} count={counts} />
          <Category catData={props.categ} onSelectedCat={id => console.log('id in indeeeeex', id)} />
        </div>

      </div>
    </>
  )
}

export async function getServerSideProps(context) {
  try {
    const categories = await axios.get(`${process.env.APP_API_URL}post-categories`)
      .then(res => res.data)
    const posts = await axios.get(`${process.env.APP_API_URL}posts`)
      .then(res => res.data)

    return {
      props: {
        categ: JSON.parse(JSON.stringify(categories)),
        posts: JSON.parse(JSON.stringify(posts)),

      }
    }
  }
  catch (error) {
    console.log('error', error);
    return {
      props: {
        categ: [],
        posts: []
      }
    }
  }
}




export default Home;